#!/bin/bash

# ==============================================================================
# Cowrie Deception Configurator v2 (with Custom Filesystem)
# Run this as the 'cowrie' user from within your cowrie installation directory.
# ==============================================================================

COWRIE_DIR="$HOME/cowrie"
NEW_HOSTNAME="pi-sensor-gateway"
SSH_BANNER="SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1"

# CHANGE THIS to the IP of your laptop/server hosting the pickle file
HOST_SERVER_IP="10.1.10.20" 
PICKLE_FILENAME="hackathon_pi.pickle"

echo "[*] Starting Advanced Cowrie Deception Setup..."

# 1. Initialize Configuration File
# ------------------------------------------------------------------------------
if [ ! -f "$COWRIE_DIR/cowrie.cfg" ]; then
    echo "[+] Creating cowrie.cfg from distribution template..."
    cp "$COWRIE_DIR/etc/cowrie.cfg.dist" "$COWRIE_DIR/cowrie.cfg"
fi

# 2. Modify Hostname and SSH Banner
# ------------------------------------------------------------------------------
echo "[+] Spoofing hostname to: $NEW_HOSTNAME"
sed -i "s/^hostname =.*/hostname = $NEW_HOSTNAME/" "$COWRIE_DIR/cowrie.cfg"

echo "[+] Spoofing SSH version banner to: $SSH_BANNER"
sed -i "s/^version =.*/version = $SSH_BANNER/" "$COWRIE_DIR/cowrie.cfg"

# 3. Download & Configure the Custom Skeleton (.pickle)
# ------------------------------------------------------------------------------
echo "[+] Fetching custom filesystem skeleton from $HOST_SERVER_IP..."
curl -s -o "$COWRIE_DIR/share/cowrie/$PICKLE_FILENAME" "http://$HOST_SERVER_IP:8000/$PICKLE_FILENAME"

# Tell Cowrie to use this new skeleton instead of the default
echo "[+] Updating cowrie.cfg to use custom filesystem..."
# First, remove any existing filesystem lines in the [shell] section to prevent duplicates
sed -i '/^filesystem =/d' "$COWRIE_DIR/cowrie.cfg"
# Add the new filesystem path under the [shell] section
sed -i "/^\[shell\]/a filesystem = share/cowrie/$PICKLE_FILENAME" "$COWRIE_DIR/cowrie.cfg"

# 4. Populate the "Meat" (HoneyFS Contents)
# ------------------------------------------------------------------------------
echo "[+] Generating realistic system files in honeyfs..."
mkdir -p "$COWRIE_DIR/honeyfs/etc"
mkdir -p "$COWRIE_DIR/honeyfs/var/www/html"

# Fake /etc/passwd (Shows multiple users)
cat << 'EOF' > "$COWRIE_DIR/honeyfs/etc/passwd"
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
pi:x:1000:1000:,,,:/home/pi:/bin/bash
webadmin:x:1001:1001:,,,:/home/webadmin:/bin/bash
mysql:x:1002:1002:MySQL Server,,,:/nonexistent:/bin/false
EOF

# Fake /etc/os-release (Proves it is a Raspberry Pi OS)
cat << 'EOF' > "$COWRIE_DIR/honeyfs/etc/os-release"
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
EOF

# Fake Database Config (Extremely juicy target)
cat << 'EOF' > "$COWRIE_DIR/honeyfs/var/www/html/config.php"
<?php
// Auto-generated by Ansible 
define('DB_SERVER', 'localhost');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', 'FAU_cyber_db_admin_99!');
define('DB_NAME', 'sensor_data_metrics');
?>
EOF

# 5. Inject a Realistic MOTD and Bait
# ------------------------------------------------------------------------------
echo "[+] Injecting fake corporate MOTD..."
cat << 'EOF' > "$COWRIE_DIR/honeyfs/etc/motd"

====================================================================
WARNING: UNAUTHORIZED ACCESS PROHIBITED
Property of Distributed Sensor Network - Node Alpha
All connections are monitored and recorded.
====================================================================
EOF

echo "[+] Generating fake .bash_history for the root user..."
mkdir -p "$COWRIE_DIR/honeyfs/root"
cat << 'EOF' > "$COWRIE_DIR/honeyfs/root/.bash_history"
ping 8.8.8.8
apt update && apt upgrade -y
nano /var/www/html/config.php
systemctl restart mariadb
ssh admin@10.1.10.55
docker-compose up -d
exit
EOF

echo "[+] Dropping fake AWS credentials..."
mkdir -p "$COWRIE_DIR/honeyfs/root/.aws"
cat << 'EOF' > "$COWRIE_DIR/honeyfs/root/.aws/credentials"
[default]
aws_access_key_id = AKIAIOSFODNN7EXAMPLE
aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
EOF

echo "[*] Deception setup complete!"
echo "[*] Please restart Cowrie to apply these changes: bin/cowrie restart"
