#!/bin/bash
# ==============================================================================
# Cowrie Deception Configurator v7 (Incremental) — Project SCALPEL
# FAU Team - eMERGE 2026 Hackathon
#
# RUN INSTRUCTIONS:
#   Run this from the Pi terminal.
#
# FEATURES:
#   - Populates advanced honeyfs (SSH configs, deep /proc/net, /etc/shadow)
#   - Randomizes file timestamps so they look realistic
#   - INCREMENTALLY updates the existing fs.pickle using bin/fsctl !
# ==============================================================================

# ---- Configuration Variables ----
COWRIE_DIR="/home/cowrie/cowrie"
NEW_HOSTNAME="raspberrypi"
SSH_BANNER="SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3"

# Fake Network/System Facts
IP_SELF="10.4.27.23"
IP_GATEWAY="10.4.27.1"
IP_ADMIN="10.4.27.55"
IP_NODE_BETA="10.4.27.21"
MAC_GATEWAY="f4:1e:57:85:0b:06"
IFACE="wlan0"
DB_PASSWORD="FAU_cyber_db_admin_99!"
DB_NAME="sensor_data_metrics"

echo "[*] Starting Incremental Cowrie Deception Setup..."

if [ ! -d "$COWRIE_DIR" ]; then
    echo "[!] Cannot find cowrie directory at $COWRIE_DIR. Did you install it somewhere else?"
    exit 1
fi

COWRIE_CFG="$COWRIE_DIR/etc/cowrie.cfg"
HONEYFS="$COWRIE_DIR/honeyfs"
PICKLE="$COWRIE_DIR/share/cowrie/fs.pickle"

# ==============================================================================
# 1. Update cowrie.cfg
# ==============================================================================
echo "[+] Setting hostname and SSH banner..."
sed -i "s/^hostname =.*/hostname = $NEW_HOSTNAME/" "$COWRIE_CFG"
grep -q "^hostname" "$COWRIE_CFG" || echo "hostname = $NEW_HOSTNAME" >> "$COWRIE_CFG"

sed -i "s/^version =.*/version = $SSH_BANNER/" "$COWRIE_CFG"
grep -q "^version" "$COWRIE_CFG" || echo "version = $SSH_BANNER" >> "$COWRIE_CFG"

# ==============================================================================
# 2. HoneyFS directories
# ==============================================================================
echo "[+] Creating honeyfs tree..."
mkdir -p "$HONEYFS/etc/cron.d" "$HONEYFS/etc/ssh" "$HONEYFS/etc/apt" \
         "$HONEYFS/var/www/html" "$HONEYFS/var/log" \
         "$HONEYFS/var/sensor-data" "$HONEYFS/proc/net" \
         "$HONEYFS/root/.aws" "$HONEYFS/root/.ssh" \
         "$HONEYFS/home/pi" "$HONEYFS/home/webadmin" "$HONEYFS/opt/sensor"

# ==============================================================================
# 3. Create Bait Files
# ==============================================================================
echo "[+] Writing bait files..."

cat << 'EOF' > "$HONEYFS/etc/passwd"
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
sshd:x:101:65534::/run/sshd:/usr/sbin/nologin
pi:x:1000:1000:,,,:/home/pi:/bin/bash
webadmin:x:1001:1001:,,,:/home/webadmin:/bin/bash
mysql:x:1002:1002:MySQL Server,,,:/nonexistent:/bin/false
EOF

cat << 'EOF' > "$HONEYFS/etc/shadow"
root:$6$rounds=656000$rAnDoMsAlT123$fakehashedpassword123456789abcdef:19200:0:99999:7:::
daemon:*:19835:0:99999:7:::
bin:*:19835:0:99999:7:::
sys:*:19835:0:99999:7:::
www-data:*:19835:0:99999:7:::
sshd:*:19835:0:99999:7:::
pi:$6$rounds=656000$aNothErSaLt456$fakehashedpassword987654321zyxwvu:19200:0:99999:7:::
webadmin:$6$rounds=656000$yEtAnOtHeR789$fakehashedpasswordabcdef123456789:19200:0:99999:7:::
mysql:!:19835:0:99999:7:::
EOF

echo "$NEW_HOSTNAME" > "$HONEYFS/etc/hostname"

cat << EOF > "$HONEYFS/etc/hosts"
127.0.0.1       localhost
127.0.1.1       $NEW_HOSTNAME
$IP_SELF        node-alpha
$IP_NODE_BETA   node-beta
$IP_ADMIN       admin
EOF

cat << 'EOF' > "$HONEYFS/etc/os-release"
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
ID=debian
EOF

cat << 'EOF' > "$HONEYFS/etc/ssh/sshd_config"
# Debian 12 sshd_config
Include /etc/ssh/sshd_config.d/*.conf
Port 22
ListenAddress 0.0.0.0
PermitRootLogin prohibit-password
PasswordAuthentication yes
X11Forwarding yes
PrintMotd no
EOF

cat << EOF > "$HONEYFS/proc/net/arp"
IP address       HW type     Flags       HW address            Mask     Device
$IP_GATEWAY      0x1         0x2         $MAC_GATEWAY         * $IFACE
EOF

cat << 'EOF' > "$HONEYFS/proc/cpuinfo"
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x4
CPU part        : 0xd0b
CPU revision    : 1
Hardware        : BCM2835
Model           : Raspberry Pi 5 Model B Rev 1.1
EOF

cat << EOF > "$HONEYFS/var/www/html/config.php"
<?php
// Auto-generated by Ansible
define('DB_SERVER', 'localhost');
define('DB_USERNAME', 'root');
define('DB_PASSWORD', '$DB_PASSWORD');
define('DB_NAME', '$DB_NAME');
?>
EOF

cat << 'EOF' > "$HONEYFS/root/.bash_history"
ping 8.8.8.8
apt update && apt upgrade -y
nano /var/www/html/config.php
systemctl restart mariadb
systemctl status apache2
cat /etc/passwd
crontab -l
mysql -u root -pFAU_cyber_db_admin_99! sensor_data_metrics
exit
EOF

cat << 'EOF' > "$HONEYFS/root/.aws/credentials"
[default]
aws_access_key_id = AKIAQX3LM7NP2RSTVW84
aws_secret_access_key = Jx7vK2mPqR9nL4wT6yB3hF8cZ1dA5eG0iUoYsNj
region = us-east-1
EOF

cat << 'EOF' > "$HONEYFS/root/.ssh/id_rsa"
-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAmZxHIKlEvFfsjnBqT9W2yPxRgcLdA6MeyOzVhN5sBrKUCXjwm1tY
9pF0DaSLoZ7iGvQuExMcPbhRfY2ANk4UXvWIqVTCDBJKmLs1n8HtZO6PQgeRy3u4vwxK2j
EXAMPLE_FAKE_KEY_DO_NOT_USE_THIS_IS_A_DECOY_IN_A_HONEYPOT_abcdefghij==
-----END OPENSSH PRIVATE KEY-----
EOF

# ==============================================================================
# 4. Randomize Timestamps
# ==============================================================================
echo "[+] Setting diverse mtimes on honeyfs files..."
python3 - "$HONEYFS" << 'PYEOF'
import os, sys, random, time
from pathlib import Path
root = Path(sys.argv[1])
random.seed(0xC0DE5CA1)
for p in sorted(root.rglob("*")):
    if p.is_symlink(): continue
    sp = str(p)
    if sp.endswith(".bash_history"): delta = random.uniform(-3600, -60)
    elif "/var/log/" in sp: delta = random.uniform(-7*86400, -60)
    elif "/proc/" in sp: delta = -random.uniform(0, 300)
    else: delta = -random.uniform(30*86400, 180*86400)
    try:
        target = time.time() + delta
        os.utime(p, (target, target))
    except OSError: pass
PYEOF

# ==============================================================================
# 5. INCREMENTAL UPDATE OF FS.PICKLE VIA FSCTL
# ==============================================================================
echo "[+] Injecting new files into existing fs.pickle..."

# We use Python to traverse honeyfs and build a massive block of fsctl commands.
# This prevents us from having to run fsctl 100 times (which is very slow).
cd "$COWRIE_DIR"

FSCTL_CMDS=$(python3 - << 'PYEOF'
import os, sys
honeyfs_dir = "/home/cowrie/cowrie/honeyfs"

# Create a list of fsctl commands
commands = []

for dirpath, dirnames, filenames in os.walk(honeyfs_dir):
    rel_dir = "/" + os.path.relpath(dirpath, honeyfs_dir).replace(os.sep, "/")
    rel_dir = "/" if rel_dir == "/." else rel_dir

    # Ensure directories exist in pickle
    for d in sorted(dirnames):
        full_dir = os.path.join(rel_dir, d).replace("//", "/")
        commands.append(f"mkdir {full_dir}")
        commands.append(f"chown 0:0 {full_dir}")

    # Ensure files exist in pickle
    for f in sorted(filenames):
        real_path = os.path.join(dirpath, f)
        fake_path = os.path.join(rel_dir, f).replace("//", "/")
        size = os.path.getsize(real_path)

        commands.append(f"touch {fake_path} {size}")

        # Adjust owners/permissions for sensitive files
        if "/.ssh" in fake_path or "/.aws" in fake_path or "shadow" in fake_path:
            commands.append(f"chmod 600 {fake_path}")

        if "/home/pi" in fake_path:
            commands.append(f"chown 1000:1000 {fake_path}")
        elif "/home/webadmin" in fake_path:
            commands.append(f"chown 1001:1001 {fake_path}")
        else:
            commands.append(f"chown 0:0 {fake_path}")

# Output commands as a single block for the shell
print("\n".join(commands))
PYEOF
)

# Run the generated commands through Cowrie's fsctl tool
echo "$FSCTL_CMDS" | ./cowrie-env/bin/python ./bin/fsctl "$PICKLE" > /dev/null 2>&1

echo "[+] fs.pickle successfully updated!"

# ==============================================================================
# 6. Restart Cowrie
# ==============================================================================
echo "[+] Restarting Cowrie..."
if [ -f "$COWRIE_DIR/bin/cowrie" ]; then
    "$COWRIE_DIR/bin/cowrie" restart
    sleep 2
    "$COWRIE_DIR/bin/cowrie" status
else
    echo "[!] Restart manually: $COWRIE_DIR/bin/cowrie restart"
fi

echo ""
echo "=== Deception Setup Complete ==="
echo "  Hostname : $NEW_HOSTNAME"
echo "  Banner   : $SSH_BANNER"
echo "  Pickle   : Incrementally updated via fsctl"
echo "  Verify   : ssh root@localhost -p 2222   password: root"
